### ISSUE TITLE
Feature/TemplateSelection

### ISSUE THREAD

**Issue by sirraminyavari** [sirraminyavari/rv-components#50]
کامپوننت Template Selection قبلا در پروژه CliqMind پیاده سازی شده است، با این تفاوت که در آن پروژه به جای SASS از Styled Components استفاده شده و انتقال آن به پروژه rv-components مستلزم تبدیل آن به SASS خواهد بود. 

Figma: https://www.figma.com/file/KuDfP66uUrk9qHJaeALH4e/RaaiVan?type=design&node-id=735-2&mode=design&t=DaqLkSzwcAZvwqTc-0

کامپوننت دارای دو نمای مختلف است:

- نمای Preview. در این حالت فرم مربوط به تمپلیت در حالتی شبیه به تکمیل فرم توسط کاربر نمایش داده می شود.
- نمای پیش فرض. در این حالت فقط عنوان فیلدهای فرم به همراه آیکون آنها نمایش داده می شود.

**نیاز به تایید:** آیا طراحی مربوط به انتخاب چند گانه تمپلیت ها موجود است؟

**Comment by ahs1375** [comment]
![Template selector](https://github.com/sirraminyavari/rv-components/assets/50149665/6d57b4b9-37e1-433e-a43e-6de424fd83fe)
نمای پیشفرض

**Comment by ahs1375** [comment]
![Uploading image.png…]()
نمای با Preview

**Comment by ahs1375** [comment]
![image](https://github.com/sirraminyavari/rv-components/assets/50149665/f45e4060-8f61-4464-86b6-13bd5a5545f1)
نمای با Preview

**Comment by ahs1375** [comment]
https://www.figma.com/file/KuDfP66uUrk9qHJaeALH4e/RaaiVan?type=design&node-id=887-183&mode=design&t=fTIiKadMgdcXM3B7-4

empty state

**Comment by ahs1375** [comment]
https://www.figma.com/file/KuDfP66uUrk9qHJaeALH4e/RaaiVan?type=design&node-id=887-756&mode=design&t=fTIiKadMgdcXM3B7-4

Multiple template selection
